//------------------------------------------------------------
// This file is automatically generated by tools. Do not modify directly.
//------------------------------------------------------------
namespace Game.Update
{
	// 实体组编号
	public enum EntityGroupId : byte
	{
		// 
		PLAYER = 1,
	}
}
