//------------------------------------------------------------
// This file is automatically generated by tools. Do not modify directly.
// Generated on: 2024-11-10 13:27:01.972
//------------------------------------------------------------
namespace Game.Update
{
	// 实体编号
	public enum EntityId : byte
	{
	}
}
