//------------------------------------------------------------
// This file is automatically generated by tools. Do not modify directly.
// Generated on: 2024-11-16 16:36:50.543
//------------------------------------------------------------
namespace Game.Update
{
	// 实体组编号
	public enum EntityGroupId : byte
	{
		// 
		PLAYER = 1,
	}
}
