//------------------------------------------------------------
// This file is automatically generated by tools. Do not modify directly.
// Generated on: 2024-11-10 02:44:18.326
//------------------------------------------------------------
namespace Game.Update
{
	// 音乐编号
	public enum MusicId : byte
	{
		// 
		BGM = 1,
	}
}
