//------------------------------------------------------------
// This file is automatically generated by tools. Do not modify directly.
// Generated on: 2024-11-16 16:36:51.005
//------------------------------------------------------------
namespace Game.Update
{
	// 音乐编号
	public enum MusicId : byte
	{
		// 
		BGM = 1,
	}
}
