//------------------------------------------------------------
// This file is automatically generated by tools. Do not modify directly.
//------------------------------------------------------------
namespace Game.Update
{
	// 音乐编号
	public enum MusicId : byte
	{
		// 
		BGM = 1,
	}
}
