//------------------------------------------------------------
// This file is automatically generated by tools. Do not modify directly.
// Generated on: 2024-11-10 13:27:02.209
//------------------------------------------------------------
namespace Game.Update
{
	// 场景编号
	public enum SceneId : byte
	{
		// 
		GAMESCENE = 1,
	}
}
