//------------------------------------------------------------
// This file is automatically generated by tools. Do not modify directly.
//------------------------------------------------------------
namespace Game.Update
{
	// 声音编号
	public enum SoundId : byte
	{
	}
}
