//------------------------------------------------------------
// This file is automatically generated by tools. Do not modify directly.
// Generated on: 2024-11-16 16:36:51.002
//------------------------------------------------------------
namespace Game.Update
{
	// 声音编号
	public enum SoundId : byte
	{
	}
}
