//------------------------------------------------------------
// This file is automatically generated by tools. Do not modify directly.
// Generated on: 2024-11-10 13:27:02.432
//------------------------------------------------------------
namespace Game.Update
{
	// 声音编号
	public enum SoundId : byte
	{
	}
}
