//------------------------------------------------------------
// This file is automatically generated by tools. Do not modify directly.
// Generated on: 2024-11-16 16:36:51.233
//------------------------------------------------------------
namespace Game.Update
{
	// 界面编号
	public enum UIFormId : byte
	{
	}
}
