//------------------------------------------------------------
// This file is automatically generated by tools. Do not modify directly.
//------------------------------------------------------------
namespace Game.Update
{
	// 界面编号
	public enum UIFormId : byte
	{
	}
}
