//------------------------------------------------------------
// This file is automatically generated by tools. Do not modify directly.
// Generated on: 2024-11-10 02:44:18.552
//------------------------------------------------------------
namespace Game.Update
{
	// 界面组编号
	public enum UIGroupId : byte
	{
		// 
		DEFAULT = 1,
	}
}
