//------------------------------------------------------------
// This file is automatically generated by tools. Do not modify directly.
// Generated on: 2024-11-16 16:36:51.008
//------------------------------------------------------------
namespace Game.Update
{
	// 界面声音编号
	public enum UISoundId : byte
	{
		// 
		Basics = 1,
	}
}
