//------------------------------------------------------------
// This file is automatically generated by tools. Do not modify directly.
//------------------------------------------------------------
namespace Game.Update
{
	// 界面声音编号
	public enum UISoundId : byte
	{
		// 
		Basics = 1,
	}
}
