//------------------------------------------------------------
// This file is automatically generated by tools. Do not modify directly.
// Generated on: 2024-11-16 16:36:51.238
//------------------------------------------------------------
namespace Game.Update
{
	// 界面控件编号
	public enum UIWidgetId : byte
	{
		// 
		SOUNDBUTTON = 1,
	}
}
