//------------------------------------------------------------
// This file is automatically generated by tools. Do not modify directly.
//------------------------------------------------------------
namespace Game.Update
{
	// 界面控件编号
	public enum UIWidgetId : byte
	{
		// 
		SOUNDBUTTON = 1,
	}
}
