
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Game.LubanTable;

namespace Game.LubanTable.Item
{
public sealed partial class ItemExchange : Luban.BeanBase
{
    public ItemExchange(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Num = _buf.ReadInt();
        PostInit();
    }

    public static ItemExchange DeserializeItemExchange(ByteBuf _buf)
    {
        return new Item.ItemExchange(_buf);
    }

    /// <summary>
    /// 道具id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 道具数量
    /// </summary>
    public readonly int Num;
    public const int __ID__ = 1458423121;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        PostResolveRef();
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "num:" + Num + ","
        + "}";
    }

    partial void PostInit();
    partial void PostResolveRef();
}
}
